const GET_BUCKET = "GET_BUCKET";
const EDIT_BUCKET = "EDIT_BUCKET";
const REMOVE_BUCKET = "REMOVE_BUCKET";
const ADD_BUCKET = "ADD_BUCKET";
const GET_TODO = "GET_TODO";
const ADD_TODO = "ADD_TODO";
const EDIT_TODO = "EDIT_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const ACTION_TODO = "ACTION_TODO";

export {
  GET_BUCKET,
  EDIT_BUCKET,
  REMOVE_BUCKET,
  ADD_BUCKET,
  GET_TODO,
  ADD_TODO,
  EDIT_TODO,
  REMOVE_TODO,
  ACTION_TODO
};
